"""create satellite observations

Revision ID: 74449d2ea8d9
Revises: 709a2d840396
Create Date: 2026-09-26 23:06:06.130715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74449d2ea8d9'
down_revision: Union[str, Sequence[str], None] = '709a2d840396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('satellite_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('water_body_id', sa.Integer(), nullable=False),
    sa.Column('satellite', sa.String(length=50), nullable=False),
    sa.Column('observation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scene_id', sa.String(length=200), nullable=False),
    sa.Column('cloud_percentage', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('observation_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_satellite_observations_id'), 'satellite_observations', ['id'], unique=False)
    op.create_index(op.f('ix_satellite_observations_water_body_id'), 'satellite_observations', ['water_body_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_satellite_observations_water_body_id'), table_name='satellite_observations')
    op.drop_index(op.f('ix_satellite_observations_id'), table_name='satellite_observations')
    op.drop_table('satellite_observations')
    # ### end Alembic commands ###
